modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "${license}"

[[mods]]
modId = "${modid}"
version = "${version}"
displayName = "${name}"
authors = "${authors}"
description = "${description}"
#logoFile = ""

[[dependencies.${modid}]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modid}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"
